spring:
  application:
    name: recipe
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  messages:
    basename: messages,validation-messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB