spring:
  application:
    name: recipe
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  messages:
    basename: messages,validation-messages